# Generated by Django 3.2.12 on 2022-04-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['user_id'], name='smart_chat__user_id_2a1f0b_idx'),
        ),
    ]
