# Generated by Django 3.2.12 on 2022-04-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_chat', '0002_make_Schedule__sent_date__nullible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='discount',
        ),
    ]
